# Посмотрим какие данные у нас есть

## Сначала посмотрим на holidays events
Согласно данным на kaggle данный датасет представляет собой информацию о выходных или праздниках в конкретные дни.

In [2]:
import pandas as pd

In [3]:
df_events = pd.read_csv('data/holidays_events.csv')
df_events.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [5]:
df_events.dtypes

date            str
type            str
locale          str
locale_name     str
description     str
transferred    bool
dtype: object

In [11]:
# Сразу разберемся с типами данных, приведем столбец date к формату datetime
df_events['date'] = pd.to_datetime(df_events['date'])

In [14]:
df_events.describe(include="all")

,date,type,locale,locale_name,description,transferred
count,350,350,350,350,350,350
unique,NaN,6,3,24,103,2
top,NaN,Holiday,National,Ecuador,Carnaval,False
freq,NaN,221,174,174,10,338
mean,2015-04-24 00:45:15.428571,NaN,NaN,NaN,NaN,NaN
min,2012-03-02 00:00:00,NaN,NaN,NaN,NaN,NaN
25%,2013-12-23 06:00:00,NaN,NaN,NaN,NaN,NaN
50%,2015-06-08 00:00:00,NaN,NaN,NaN,NaN,NaN
75%,2016-07-03 00:00:00,NaN,NaN,NaN,NaN,NaN
max,2017-12-26 00:00:00,NaN,NaN,NaN,NaN,NaN

In [15]:
df_events['type'].value_counts()

type
Holiday       221
Event          56
Additional     51
Transfer       12
Bridge          5
Work Day        5
Name: count, dtype: int64

In [17]:
df_events['locale'].value_counts()

locale
National    174
Local       152
Regional     24
Name: count, dtype: int64

In [21]:
df_events['locale_name'].value_counts().head(10)

locale_name
Ecuador      174
Quito         13
Riobamba      12
Guaranda      12
Latacunga     12
Ambato        12
Guayaquil     11
Cuenca         7
Ibarra         7
Manta          6
Name: count, dtype: int64

In [22]:
df_events['description'].value_counts()

description
Carnaval                           10
Fundacion de Cuenca                 7
Fundacion de Ibarra                 7
Fundacion de Manta                  6
Provincializacion de Cotopaxi       6
                                   ..
Traslado Fundacion de Guayaquil     1
Puente Dia de Difuntos              1
Recupero Puente Dia de Difuntos     1
Traslado Primer dia del ano         1
Traslado Fundacion de Quito         1
Name: count, Length: 103, dtype: int64

In [23]:
df_events['transferred'].value_counts()

transferred
False    338
True      12
Name: count, dtype: int64